### ISSUE TITLE
Prevent orientationChanged been called when only support Portrait

### ISSUE THREAD

**Issue by FelipeDocil** [uzysjung/UzysAnimatedGifPullToRefresh#10]
In my project I don't support any others orientation, except Portrait. But everytime I "rotate" the phone every changes in `UIDeviceOrientation` and `UIInterfaceOrientation`, the method `orientationChanged:` is called.

That causes my tableView scrolls to top. And that's what I'd like to prevent

**Comment by marcelosalloum** [comment]
+1

I am also having this problem. Despite the results of this lib being awesomely beautiful, it's painful that every time the orientation changes the table goes to the top. 

Being able to disable that would be really good for my app.

**Comment by uzysjung** [comment]
Thanks for the reporting. I'll fix it

**Comment by uzysjung** [comment]
fixed 
check latest commit
