### ISSUE TITLE
It doesn't work on page menu view.

### ISSUE THREAD

**Issue by nagaho** [uzysjung/UzysAnimatedGifPullToRefresh#12]
I use it on scroll page menu view. (like PageMenu https://github.com/uacaps/PageMenu) It works on 1st page but doesn't work on 2nd+ pages. It just doesn't display images, probably images'x position is wrong. Any Idea? Thanks.

**Comment by uzysjung** [comment]
Page menu structure 

Vc- 1st scrollview - vc(it will remove when you scroll) - 2st scrollview

You should add to 1st scrollview

**Comment by nagaho** [comment]
That's right but I have not use that lib and remove vc. Btw It seems to work on ver 0.9.5 but doesn't work on ver 0.9.6.

**Comment by uzysjung** [comment]
Hello, I tested on PageMenu with UzysAnimatedGifPullToRefresh . it works perfectly.

**Comment by nagaho** [comment]
It works perfectly with this fix on ver 0.9.6. I will folk it. Thank you.

UzysAnimatedGifActivityIndicator.m
-self.center = CGPointMake(self.scrollView.center.x, (contentOffset.y+ self.originalTopInset)/2);
+self.center = CGPointMake(self.center.x, (contentOffset.y+ self.originalTopInset)/2);
