### ISSUE TITLE
Issue using it with the library SKSTableView together.

### ISSUE THREAD

**Issue by mariovillamizar** [uzysjung/UzysAnimatedGifPullToRefresh#15]
Hello friend. Congratulations for this great control. I'm having problems when I try to use your control together to another control named SKSTableView. When I pull to refresh, the tableview change the position.

**Comment by uzysjung** [comment]
please checked SKSTableView example project scroll indicator. when you scroll to top. but scroll indicator do not reachead top. that makes some problem. because section height , cell height is not correct.

**Comment by uzysjung** [comment]
you can solve this problem
to put [self.tableView addPullToRefreshActionHandler..] in (void)viewDidAppear:(BOOL)animated

**Comment by uzysjung** [comment]
SKSTableView ViewController.xib -> constraint Vertical Space - TableView - View 
-> First Item TableView.top 
relation equal 
second Item superview.top

**Comment by uzysjung** [comment]
or you can add [self.tableView addPullToRefreshActionHandler...] in (void)viewDidAppear:(BOOL)animated....

**Comment by mariovillamizar** [comment]
Thanks @uzysjung. The first observation helped me a lot.

**Comment by mariovillamizar** [comment]
Hello @uzysjung. Can you comment this line 134 in #import "UzysAnimatedGifActivityIndicator.m" --> NSLog(@"offset %f",self.scrollView.contentOffset.y);  This is silly, but sometimes it's uncomfortable. Thank you.
