### ISSUE TITLE
iOS 7 Navigation Bar issue

### ISSUE THREAD

**Issue by mehmettaskiner** [uzysjung/UzysAnimatedGifPullToRefresh#6]
Hello,

If navigation bar is translucent on iOS 7, tableView will stay behind navigation bar. 

If I set to not translucent, everything is normal.

**Comment by heliumdice** [comment]
Hey @mehmettaskiner Did you manage to solve this problem with the gap that was appearing under the nav bar? I am getting a similar problem. 

![pull to refresh nav bar gap](https://cloud.githubusercontent.com/assets/1543954/6191937/57fcb20a-b3a5-11e4-8635-98d96eb244fc.png)

I have a table view within a view controller. That table view has a custom class associated with it. In that custom classes initialiser (which is called by initWithCoder) I call addPullToRefreshActionHandler on self.

[self addPullToRefreshActionHandler:^{
        [s refreshNow:YES];
    }.....

I am getting inconsistent behaviour when navigating through my app. Sometimes this gap under the nav bar is present and sometimes it disappears at random times even after stopPullToRefreshAnimation has been called. 

I was wondering if you could shed any light on the problem. I have probably not been very clear with my explanation. Let me know if you need anymore details. 

Thanks.

**Comment by heliumdice** [comment]
I should add even when I set the content offset of the table to be 0 this gap still appears.

**Comment by mehmettaskiner** [comment]
@heliumdice i encountered same issues, so i decided to use native UIRefreshControl

**Comment by uzysjung** [comment]
Hi, I checked. It works fine. 
please check below
1. move 'addPullToRefreshActionHandler ' to viewDidApper . 
2. and you can manually change contentInset, In viewdidLoad, put in  {
   self.automaticallyAdjustsScrollViewInsets = NO;
   self.tableView.contentInset = UIEdgeInsetsMake(0, 0, 0, 0);
}

**Comment by esusatyo** [comment]
I was having this problem, and my solution was doing this after setting up the refresh control:

```
self.navigationController.navigationBar.translucent = NO;
[self.eventTableView addTopInsetInPortrait:0.0f TopInsetInLandscape:0.0f];
```
