### ISSUE TITLE
Non translucent navigation bar & iOS 8

### ISSUE THREAD

**Issue by NtskX** [uzysjung/UzysAnimatedGifPullToRefresh#7]
Hey,

I'm trying to use your project with a non-translucent bar on iOS 8 and the tableview insets are not correct.
See here : http://cl.ly/image/2P2A3C0H250N and http://cl.ly/image/0R1y2b3S3j2N

I tried setting the tableview.contentInset to 0 top but the trigger seems to start at 64 (status bar + navigation bar height).

Using your sample project :
• Navigation bar non translucent
• addPullToRefreshActionHandler: in viewDidAppear
• self.automaticallyAdjustsScrollViewInsets = NO; and self.tableView.contentInset = UIEdgeInsetsMake(0, 0, 0, 0); in viewDidLoad

Thanks !

**Comment by uzysjung** [comment]
Thanks for the bug reporting. 
For a convenience, I assume only translucent navigation bar. 

therefore if you use non-translucent navigation bar , you just set [self.tableView addTopInsetInPortait:0 TopInsetInLandscape:0] after addPullToRefreshActionHandler like sample project.

sooner or later. support non-translucent navigation bar using method. 

thanks.
