### ISSUE TITLE
UINavigationController issue

### ISSUE THREAD

**Issue by oyh520200** [uzysjung/UzysAnimatedGifPullToRefresh#8]
code:[navi.navigationBar setBackgroundImage:[UIImage imageWithColor: [UIColor colorWithWhite:0 alpha:1.0]]] forBarMetrics:UIBarMetricsDefault];
There is a issue, contentOffset.top should be 100,and  your codes should not work.When alpha is <=1.0,It should work.

**Comment by oyh520200** [comment]
ah.When bar.translucent=NO, issue occur~

**Comment by uzysjung** [comment]
Hi please check #7 issue

**Comment by oyh520200** [comment]
HI,thanks, @uzysjung.
the orientation support is using observation of UIDeviceOrientation and the topInset should be wrong any times.When landspace it may be 64.
I Modify to observe UIApplicationDidChangeStatusBarOrientation,and Override this method.It works well.
- (void)orientationChange:(UIInterfaceOrientation)orientation {
    if(UIInterfaceOrientationIsLandscape(orientation))
    {
        if(cNotEqualFloats( self.landscapeTopInset , 0.0 , cDefaultFloatComparisonEpsilon))
            self.originalTopInset = self.landscapeTopInset;
    }
    else
    {
        if(cNotEqualFloats( self.portraitTopInset , 0.0 , cDefaultFloatComparisonEpsilon))
            self.originalTopInset = self.portraitTopInset;
    }
    
//    if(self.state == UZYSGIFPullToRefreshStateLoading)
//    {
//        if( self.isVariableSize ) {
//            [self setFrameSizeByLoadingImage];
//            
//        } else {
//            [self setFrameSizeByProgressImage];
//        }
//        [self setupScrollViewContentInsetForLoadingIndicator:^{
//            
//        } animation:NO];
//    }
//    else
//    {
//        [self setFrameSizeByProgressImage];
//        [self resetScrollViewContentInset:^{
//            
//        } animation:NO];
//    }
//    self.alpha = 1.0f;


}

**Comment by uzysjung** [comment]
please check #7.
 method below, you can adjust topinset when  orientation occur too.
[self.tableView addTopInsetInPortait:0 TopInsetInLandscape:0 ];

It works well.
