### ISSUE TITLE
Using tableview instead of UItableviewcontroller

### ISSUE THREAD

**Issue by jianglin612** [uzysjung/UzysAnimatedGifPullToRefresh#9]
//pull to refresh stuff
    __weak typeof(self) weakSelf =self;
    [self.postTableView addPullToRefreshActionHandler:^{
        [weakSelf insertRowAtTop];
    }
    ProgressImagesGifName:@"spinner_dropbox@2x.gif"
    LoadingImagesGifName:@"run@2x.gif"
    ProgressScrollThreshold:60
    LoadingImageFrameRate:30]

Using this gives an error because weakSelf does not insertRowAtTop method. How would I fix this?

**Comment by uzysjung** [comment]
insertRowAtTop is the example method that I explain that how to use.  you make your own method as a reference.
